# Generated by Django 6.0 on 2025-12-04 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ferias', 'Férias'), ('reembolso', 'Reembolso'), ('treinamento', 'Treinamento')], help_text='Tipo da solicitação: férias, reembolso ou treinamento', max_length=20, verbose_name='Tipo de Solicitação')),
                ('titulo', models.CharField(help_text='Título descritivo da solicitação', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(help_text='Descrição detalhada da solicitação', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='pendente', help_text='Status atual da solicitação', max_length=20, verbose_name='Status')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor monetário (obrigatório para reembolsos e treinamentos)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor')),
                ('data_inicio', models.DateField(blank=True, help_text='Data de início (obrigatório para férias e treinamentos)', null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Data de término (obrigatório para férias e treinamentos)', null=True, verbose_name='Data de Término')),
                ('solicitante', models.CharField(help_text='Nome do colaborador solicitante', max_length=200, verbose_name='Solicitante')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais ou motivo de rejeição', verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['tipo', 'status'], name='solicitatio_tipo_d137db_idx'), models.Index(fields=['solicitante'], name='solicitatio_solicit_a651a8_idx'), models.Index(fields=['-data_criacao'], name='solicitatio_data_cr_d4b838_idx')],
            },
        ),
    ]
